# Generated by Django 5.0.4 on 2024-11-08 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="users",
            field=models.ManyToManyField(
                related_name="chatRooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
