# Generated by Django 5.0.4 on 2024-11-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_recipient_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatroom",
            ),
        ),
    ]
