# Generated by Django 5.0.4 on 2024-06-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar_name', models.CharField(max_length=40, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AvatarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_db', models.ImageField(upload_to='img/')),
            ],
            options={
                'db_table': 'avatar_images',
            },
        ),
        migrations.CreateModel(
            name='Auths',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.userprofiles')),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'auths',
            },
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='avatar_image_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.avatarimages'),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('request', 'Request'), ('peding', 'Pedding'), ('accept', 'Accept'), ('block', 'Block')], max_length=10)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_profile', to='api.userprofiles')),
                ('my_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to='api.userprofiles')),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='MatchHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('player1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='api.userprofiles')),
                ('player2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='api.userprofiles')),
                ('win_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_win', to='api.userprofiles')),
            ],
            options={
                'db_table': 'match_histories',
            },
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('my_id', 'friend_id'), name='unique_player_pair'),
        ),
    ]
