# Generated by Django 5.0.6 on 2024-06-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('peding', 'Pedding'), ('accept', 'Accept'), ('block', 'Block')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('my_id', 'friend_id'), name='unique_player_pair'),
        ),
    ]
