# Generated by Django 5.0.4 on 2024-07-29 15:29

import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=pong.models.gen_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
