# Generated by Django 5.0.4 on 2024-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="size",
            field=models.IntegerField(default=2),
        ),
    ]
