# Generated by Django 5.0.4 on 2024-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0002_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="number_of_player",
            field=models.IntegerField(default=0),
        ),
    ]
