# Generated by Django 5.0.4 on 2024-09-07 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0002_room_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pong.room"
            ),
        ),
    ]
