# Generated by Django 5.0.4 on 2024-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0003_game_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="game_type",
            field=models.CharField(default="VERSUS", max_length=255),
        ),
    ]
