# Generated by Django 5.0.4 on 2024-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0007_tournament_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(default="OPEN", max_length=255),
        ),
    ]
