# Generated by Django 5.0.4 on 2024-10-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0008_alter_tournament_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pong.tournament",
            ),
        ),
    ]
