# Generated by Django 5.0.4 on 2024-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0009_game_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
