# Generated by Django 5.0.4 on 2024-11-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0010_room_hide"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
