# Generated by Django 5.0.4 on 2024-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0011_delete_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="tour_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
