# Generated by Django 5.0.4 on 2024-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0013_matchhistory_status_tourround"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchhistory",
            name="mtype",
            field=models.CharField(default="VERSUS", max_length=255),
        ),
    ]
