# Generated by Django 5.0.4 on 2024-12-05 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0014_matchhistory_mtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="user_joined",
            field=models.ManyToManyField(
                related_name="tournament_user_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
