include:
  - elk/docker-compose.yml

services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - backend
      - elastic

  backend: 
    build: backend
    ports: 
      - '8132:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - logstash
    networks:
      - backend
    env_file:
      - ./backend/.env
  
  nginx:
    build: nginx
    ports:
      - '4443:443'
      - '8080:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/frontend/
    depends_on:
      - backend
    networks:
      - backend
      - frontend

  redis:
    image: redis:latest
    restart: unless-stopped
    # ports:
    #   - 6801:6379
    networks:
      - backend
      - elastic

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - backend
  #     - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge