# include:
#   - elk/docker-compose.yml

services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5439:5432'
    networks:
      - backend

  backend: 
    build: backend
    ports: 
      - '8132:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
      # - logstash
    networks:
      - backend
    env_file:
      - ./backend/.env
  
  nginx:
    build: nginx
    ports:
      - '443:443'
      - '8001:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/frontend/
    depends_on:
      - backend
    networks:
      - backend
      - frontend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6801:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge