# Generated by Django 5.0.4 on 2024-07-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0003_rename_avatar_name_user_display_name_user_about_me_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="about_me",
        ),
    ]
