# Generated by Django 5.0.4 on 2024-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0004_remove_user_about_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(default="PENDING", max_length=255),
        ),
        migrations.DeleteModel(
            name="FriendList",
        ),
    ]
