# Generated by Django 5.0.4 on 2024-07-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0006_user_frind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="frind",
            new_name="friend",
        ),
    ]
