# Generated by Django 5.0.4 on 2024-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0007_rename_frind_user_friend"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("file_db", models.ImageField(upload_to="img/")),
            ],
        ),
    ]
