# Generated by Django 5.0.4 on 2024-07-21 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0009_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
