# Generated by Django 5.0.4 on 2024-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuac", "0011_authsession_mem"),
    ]

    operations = [
        migrations.AddField(
            model_name="authsession",
            name="in_game",
            field=models.BooleanField(default=False),
        ),
    ]
